[package]
name = "network_check"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ping = "0.4.0"
dns-lookup = "1.0.8"
itertools = "0.10.5"
chrono = "0.4.22"