[package]
name = "binary_generator"
version = "0.1.0"
authors = ["Martin K. <martin.awake1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
num-bigint = "0.4.0"